# YOLO Dataset Configuration for Vertebrae Fracture Detection

# Dataset paths
path: ../data/processed  # Dataset root path
train: train/images      # Training images relative to path
val: val/images         # Validation images relative to path
test: test/images       # Test images relative to path

# Classes
nc: 2                   # Number of classes
names: ['normal', 'fracture']  # Class names

# Data preprocessing parameters
image_size: 640         # Target image size
window_center: 40       # CT windowing center (HU)
window_width: 400       # CT windowing width (HU)
slice_thickness: 1      # Slice thickness for axial slices

# Data augmentation (training)
augmentation:
  horizontal_flip: 0.5
  vertical_flip: 0.2
  rotation: 0.5
  brightness_contrast: 0.3
  gaussian_blur: 0.2
  random_gamma: 0.2
  elastic_transform: 0.3
  
# Dataset statistics
stats:
  mean: [0.485]         # Normalization mean
  std: [0.229]          # Normalization std

# Split information (from existing Sakaguchi_file structure)
splits:
  train_patients: 24
  val_patients: 6
  test_patients: 8
  
# Medical image specific settings
medical:
  modality: "CT"
  body_part: "spine"
  plane: "axial"
  fracture_types: ["compression", "burst", "chance"]